Add 3 times retry for osd bootstrap
Signed-off-by: Ryan Liang <jiallian@amazon.com>

diff --git a/.github/workflows/cypress-e2e-reporting-test.yml b/.github/workflows/cypress-e2e-reporting-test.yml
--- a/.github/workflows/cypress-e2e-reporting-test.yml
+++ b/.github/workflows/cypress-e2e-reporting-test.yml
@@ -112,17 +112,25 @@ jobs:
           echo "Installing yarn ${{ steps.tool-versions.outputs.yarn_version }}"
           npm i -g yarn@${{ steps.tool-versions.outputs.yarn_version }}
           yarn cache clean
-          yarn add sha.js
         working-directory: OpenSearch-Dashboards
         shell: bash
 
       - name: OpenSearch Dashboards Plugin Bootstrap
-        uses: nick-fields/retry@v1
-        with:
-          timeout_minutes: 30
-          max_attempts: 3
-          command: yarn osd bootstrap
-          path: OpenSearch-Dashboards
+        run: |
+          max_retries=3
+          count=0
+          until yarn osd bootstrap; do
+            exit_code=$?
+            count=$(($count + 1))
+            echo "Attempt $count/$max_retries failed with exit code $exit_code, retrying..."
+            if [ $count -ge $max_retries ]; then
+              echo "Reached maximum retry attempts, stopping..."
+              exit $exit_code
+            fi
+            sleep 5 # Wait for 5 seconds before retrying
+          done
+        working-directory: OpenSearch-Dashboards
+        shell: bash
 
       - name: Run Opensearch Dashboards with Dashboards Reporting Plugin Installed
         run: |
